name: Trigger Sync Workflow

on:
  schedule:
    - cron: "0 19 * * *" 
  workflow_dispatch:

# 需要添加权限配置
permissions:
  contents: read
  actions: write

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Print Debug Info
        run: |
          echo "Running at: $(date)"
          echo "Repository: ${{ github.repository }}"
          echo "Event name: ${{ github.event_name }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Trigger type: ${{ github.event.schedule }}"
          
      - name: Trigger Sync Workflow
        run: |
          echo "Triggering workflow..."
          echo "Target repository: solanab/ios_rule_script_add_sing_box"
          echo "Event type: sync_upstream"
          TOKEN_LENGTH=$(echo -n "${{ secrets.PAT_TOKEN }}" | wc -c)
          echo "Using token length: $TOKEN_LENGTH characters"
          
          response=$(curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
            -w "\n%{http_code}" \
            https://api.github.com/repos/solanab/ios_rule_script_add_sing_box/dispatches \
            -d '{"event_type":"sync_upstream"}')
          
          status_code=$(echo "$response" | tail -n1)
          response_body=$(echo "$response" | head -n-1)
          
          echo "Status code: $status_code"
          echo "Response: $response_body"
          
          if [[ $status_code != 2* ]]; then
            echo "Failed to trigger workflow"
            exit 1
          fi 